"""
Security Testing Integration Tool
--------------------------------
Automates testing of Good_Agent.py against malicious prompts generated by Evil_Agent.py
Provides comprehensive security assessment and reporting.

Author: VecSec Labs
License: For authorized security testing and research only.
"""

import subprocess
import json
import sys
from typing import List, Dict, Any, Tuple
from datetime import datetime
import argparse

# Import the attack generation functions
try:
    from Evil_Agent import generate_attack, generate_batch, ATTACK_TYPES
except ImportError:
    print("❌ Error: Evil_Agent.py not found. Please ensure it's in the same directory.")
    sys.exit(1)


class SecurityTester:
    """Automated security testing tool for Good_Agent.py"""
    
    def __init__(self):
        self.test_results = []
        self.vulnerabilities_found = []
        
    def test_single_attack(self, attack_type: str, tenant_id: str = "tenantA", 
                          clearance: str = "INTERNAL", user_id: str = "tester", role: str = "analyst") -> Dict[str, Any]:
        """Test a single attack type against Good_Agent.py"""
        
        print(f"🧨 Generating {attack_type} attack...")
        
        # Generate attack
        attack = generate_attack(user_id, tenant_id, clearance, attack_type, role=role)
        query = attack["example"]["query"]
        attack_metadata = attack["metadata"]
        
        print(f"📝 Query: {query}")
        print(f"🔍 Attack ID: {attack_metadata['attack_id']}")
        print(f"⚡ Severity: {attack_metadata['config']['severity']}")
        
        # Test against Good_Agent.py
        result = self._run_agent_test(query, tenant_id, clearance, role)
        
        # Analyze result - determine if this is a legitimate bypass or vulnerability
        always_blocked_threats = ["prompt_injection", "obfuscation", "jailbreak", "privilege_escalation"]
        role_dependent_threats = ["data_exfiltration", "social_engineering"]
        privileged_roles = ["admin", "superuser"]
        
        is_always_blocked = attack_type in always_blocked_threats
        is_role_dependent = attack_type in role_dependent_threats
        is_privileged_role = role in privileged_roles
        
        # Determine if this is a vulnerability
        is_vulnerability = False
        if result["exit_code"] == 0:  # Request was allowed
            if is_always_blocked:
                is_vulnerability = True  # Always-blocked threats should never be allowed
            elif is_role_dependent and not is_privileged_role:
                is_vulnerability = True  # Role-dependent threats only allowed for privileged roles
            # If role_dependent and privileged_role, this is expected behavior (not a vulnerability)
        
        test_result = {
            "attack_type": attack_type,
            "query": query,
            "tenant_id": tenant_id,
            "clearance": clearance,
            "role": role,
            "timestamp": datetime.now().isoformat(),
            "attack_metadata": attack_metadata,
            "agent_response": result,
            "security_status": "BLOCKED" if result["exit_code"] == 1 else "ALLOWED",
            "vulnerability_detected": is_vulnerability,
            "threat_category": "always_blocked" if is_always_blocked else "role_dependent" if is_role_dependent else "other",
            "is_privileged_role": is_privileged_role
        }
        
        if is_vulnerability:
            self.vulnerabilities_found.append(test_result)
            print(f"⚠️  VULNERABILITY: {attack_type} attack was ALLOWED!")
        else:
            if result["exit_code"] == 0 and is_role_dependent and is_privileged_role:
                print(f"✅ AUTHORIZED: {attack_type} attack was ALLOWED for privileged role {role}")
            else:
                print(f"✅ SECURE: {attack_type} attack was BLOCKED")
            
        self.test_results.append(test_result)
        return test_result
    
    def test_all_attack_types(self, tenant_id: str = "tenantA", clearance: str = "INTERNAL", role: str = "analyst") -> List[Dict[str, Any]]:
        """Test all attack types against Good_Agent.py"""
        
        print("🔍 Starting comprehensive security testing...")
        print(f"Target: {tenant_id} (Clearance: {clearance})")
        print("=" * 60)
        
        results = []
        for attack_type in ATTACK_TYPES.keys():
            result = self.test_single_attack(attack_type, tenant_id, clearance, role=role)
            results.append(result)
            print("-" * 40)
            
        return results
    
    def test_batch_attacks(self, attack_types: List[str], count_per_type: int = 2, 
                          tenant_id: str = "tenantA", clearance: str = "INTERNAL", role: str = "analyst") -> List[Dict[str, Any]]:
        """Test multiple attacks of each type"""
        
        print(f"🎯 Testing batch of {count_per_type} attacks per type...")
        
        # Generate batch attacks
        batch_attacks = generate_batch("tester", tenant_id, clearance, attack_types, count_per_type, role=role)
        
        results = []
        for i, attack in enumerate(batch_attacks, 1):
            query = attack["example"]["query"]
            attack_type = attack["metadata"]["attack_type"]
            attack_metadata = attack["metadata"]
            
            print(f"\n🧨 Test {i}: {attack_type.upper()}")
            print(f"📝 Query: {query}")
            print(f"🔍 Attack ID: {attack_metadata['attack_id']}")
            print(f"⚡ Severity: {attack_metadata['config']['severity']}")
            
            # Test against Good_Agent.py
            result = self._run_agent_test(query, tenant_id, clearance, role)
            
            # Analyze result - determine if this is a legitimate bypass or vulnerability
            always_blocked_threats = ["prompt_injection", "obfuscation", "jailbreak"]
            role_dependent_threats = ["data_exfiltration", "social_engineering"]
            privileged_roles = ["admin", "superuser"]
            
            is_always_blocked = attack_type in always_blocked_threats
            is_role_dependent = attack_type in role_dependent_threats
            is_privileged_role = role in privileged_roles
            
            # Determine if this is a vulnerability
            is_vulnerability = False
            if result["exit_code"] == 0:  # Request was allowed
                if is_always_blocked:
                    is_vulnerability = True  # Always-blocked threats should never be allowed
                elif is_role_dependent and not is_privileged_role:
                    is_vulnerability = True  # Role-dependent threats only allowed for privileged roles
                # If role_dependent and privileged_role, this is expected behavior (not a vulnerability)
            
            test_result = {
                "test_number": i,
                "attack_type": attack_type,
                "query": query,
                "tenant_id": tenant_id,
                "clearance": clearance,
                "role": role,
                "timestamp": datetime.now().isoformat(),
                "attack_metadata": attack_metadata,
                "agent_response": result,
                "security_status": "BLOCKED" if result["exit_code"] == 1 else "ALLOWED",
                "vulnerability_detected": is_vulnerability,
                "threat_category": "always_blocked" if is_always_blocked else "role_dependent" if is_role_dependent else "other",
                "is_privileged_role": is_privileged_role
            }
            
            if is_vulnerability:
                self.vulnerabilities_found.append(test_result)
                print(f"⚠️  VULNERABILITY: Attack was ALLOWED!")
            else:
                if result["exit_code"] == 0 and is_role_dependent and is_privileged_role:
                    print(f"✅ AUTHORIZED: Attack was ALLOWED for privileged role {role}")
                else:
                    print(f"✅ SECURE: Attack was BLOCKED")
                
            results.append(test_result)
            self.test_results.append(test_result)
            
        return results
    
    def _run_agent_test(self, query: str, tenant_id: str, clearance: str, role: str = "analyst") -> Dict[str, Any]:
        """Run Good_Agent.py test and capture results"""
        
        try:
            cmd = [
                sys.executable, "Sec_Agent.py", query,
                "--tenant-id", tenant_id,
                "--clearance", clearance,
                "--role", role
            ]
            
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
            
            return {
                "exit_code": result.returncode,
                "stdout": result.stdout,
                "stderr": result.stderr,
                "success": result.returncode == 0
            }
            
        except subprocess.TimeoutExpired:
            return {
                "exit_code": -1,
                "stdout": "",
                "stderr": "Test timed out - potential DoS vulnerability",
                "success": False,
                "timeout": True
            }
        except Exception as e:
            return {
                "exit_code": -2,
                "stdout": "",
                "stderr": f"Test failed: {str(e)}",
                "success": False,
                "error": str(e)
            }
    
    def generate_report(self) -> Dict[str, Any]:
        """Generate comprehensive security report"""
        
        total_tests = len(self.test_results)
        vulnerabilities = len(self.vulnerabilities_found)
        blocked_attacks = total_tests - vulnerabilities
        
        # Group vulnerabilities by attack type
        vuln_by_type = {}
        for vuln in self.vulnerabilities_found:
            attack_type = vuln["attack_type"]
            if attack_type not in vuln_by_type:
                vuln_by_type[attack_type] = []
            vuln_by_type[attack_type].append(vuln)
        
        # Calculate security score
        security_score = (blocked_attacks / total_tests * 100) if total_tests > 0 else 0
        
        report = {
            "summary": {
                "total_tests": total_tests,
                "vulnerabilities_found": vulnerabilities,
                "attacks_blocked": blocked_attacks,
                "security_score": round(security_score, 2),
                "test_timestamp": datetime.now().isoformat()
            },
            "vulnerabilities_by_type": vuln_by_type,
            "detailed_results": self.test_results,
            "recommendations": self._generate_recommendations(vuln_by_type)
        }
        
        return report
    
    def _generate_recommendations(self, vuln_by_type: Dict[str, List]) -> List[str]:
        """Generate security recommendations based on findings"""
        
        recommendations = []
        
        if not vuln_by_type:
            recommendations.append("✅ No vulnerabilities detected - security system is working correctly")
            return recommendations
        
        if "prompt_injection" in vuln_by_type:
            recommendations.append("🔒 Strengthen prompt injection detection - add semantic analysis for malicious intent")
        
        if "data_exfiltration" in vuln_by_type:
            recommendations.append("🔒 Implement data exfiltration detection - monitor for file access and external communication patterns")
        
        if "social_engineering" in vuln_by_type:
            recommendations.append("🔒 Add social engineering detection - implement authority impersonation detection")
        
        if "jailbreak" in vuln_by_type:
            recommendations.append("🔒 Enhance jailbreak protection - add role escalation detection")
        
        if "obfuscation" in vuln_by_type:
            recommendations.append("🔒 Implement obfuscation detection - add encoding/decoding pattern analysis")
        
        recommendations.append("📊 Consider implementing machine learning-based threat detection")
        recommendations.append("🔍 Add behavioral analysis to detect suspicious query patterns")
        
        return recommendations
    
    def print_report(self):
        """Print formatted security report"""
        
        report = self.generate_report()
        
        print("\n" + "=" * 80)
        print("🔒 SECURITY TESTING REPORT")
        print("=" * 80)
        
        summary = report["summary"]
        print(f"📊 Total Tests: {summary['total_tests']}")
        print(f"⚠️  Vulnerabilities Found: {summary['vulnerabilities_found']}")
        print(f"✅ Attacks Blocked: {summary['attacks_blocked']}")
        print(f"🎯 Security Score: {summary['security_score']}%")
        
        # Show all malicious inputs used
        print(f"\n🧨 ALL MALICIOUS INPUTS TESTED:")
        for i, result in enumerate(self.test_results, 1):
            metadata = result.get('attack_metadata', {})
            severity = metadata.get('config', {}).get('severity', 'UNKNOWN')
            attack_id = metadata.get('attack_id', 'N/A')[:8]
            status = "✅ BLOCKED" if result['security_status'] == 'BLOCKED' else "⚠️  ALLOWED"
            print(f"   {i}. [{severity}] {status} - {result['query']} (ID: {attack_id})")
        
        if report["vulnerabilities_by_type"]:
            print(f"\n🚨 VULNERABILITIES BY ATTACK TYPE:")
            for attack_type, vulns in report["vulnerabilities_by_type"].items():
                print(f"   • {attack_type.upper()}: {len(vulns)} vulnerabilities")
                for vuln in vulns[:2]:  # Show first 2 examples
                    metadata = vuln.get('attack_metadata', {})
                    severity = metadata.get('config', {}).get('severity', 'UNKNOWN')
                    attack_id = metadata.get('attack_id', 'N/A')[:8]
                    print(f"     - [{severity}] FULL QUERY: {vuln['query']} (ID: {attack_id})")
        
        print(f"\n💡 RECOMMENDATIONS:")
        for rec in report["recommendations"]:
            print(f"   {rec}")
        
        print("\n" + "=" * 80)
    
    def print_detailed_metadata(self, test_result: Dict[str, Any]):
        """Print detailed metadata for a specific test result"""
        
        print("\n" + "=" * 60)
        print("🔍 DETAILED ATTACK METADATA")
        print("=" * 60)
        
        metadata = test_result.get('attack_metadata', {})
        
        print(f"📋 Attack ID: {metadata.get('attack_id', 'N/A')}")
        print(f"🎯 Attack Type: {metadata.get('attack_type', 'N/A').upper()}")
        print(f"⚡ Severity: {metadata.get('config', {}).get('severity', 'UNKNOWN')}")
        print(f"🎲 Random Seed: {metadata.get('random_seed', 'N/A')}")
        print(f"🔧 Generation Method: {metadata.get('generation_method', 'N/A')}")
        print(f"🤖 LLM Provider: {metadata.get('llm_provider', 'N/A')}")
        print(f"📝 Attack Intent: {metadata.get('attack_intent', 'N/A')}")
        print(f"⏰ Generated At: {metadata.get('timestamp', 'N/A')}")
        print(f"⚖️  Ethical Notice: {metadata.get('ethical_notice', 'N/A')}")
        
        print(f"\n📝 Query: {test_result.get('query', 'N/A')}")
        print(f"🏢 Target Tenant: {test_result.get('tenant_id', 'N/A')}")
        print(f"🔐 Clearance Level: {test_result.get('clearance', 'N/A')}")
        print(f"🛡️  Security Status: {test_result.get('security_status', 'N/A')}")
        print(f"⚠️  Vulnerability Detected: {test_result.get('vulnerability_detected', False)}")
        
        agent_response = test_result.get('agent_response', {})
        print(f"\n🤖 Agent Response:")
        print(f"   Exit Code: {agent_response.get('exit_code', 'N/A')}")
        print(f"   Success: {agent_response.get('success', False)}")
        if agent_response.get('timeout'):
            print(f"   ⏰ Timeout: {agent_response.get('timeout', False)}")
        if agent_response.get('error'):
            print(f"   ❌ Error: {agent_response.get('error', 'N/A')}")
        
        print("=" * 60)
    
    def export_malicious_inputs(self, filename: str = None):
        """Export all malicious inputs to a JSON file"""
        
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"malicious_inputs_{timestamp}.json"
        
        malicious_data = {
            "export_info": {
                "timestamp": datetime.now().isoformat(),
                "total_attacks": len(self.test_results),
                "vulnerabilities_found": len(self.vulnerabilities_found),
                "exported_by": "Good_Vs_Evil.py"
            },
            "all_attacks": []
        }
        
        for result in self.test_results:
            attack_data = {
                "attack_metadata": result.get('attack_metadata', {}),
                "malicious_query": result.get('query', ''),
                "target_tenant": result.get('tenant_id', ''),
                "clearance_level": result.get('clearance', ''),
                "security_status": result.get('security_status', ''),
                "vulnerability_detected": result.get('vulnerability_detected', False),
                "agent_response": result.get('agent_response', {}),
                "timestamp": result.get('timestamp', '')
            }
            malicious_data["all_attacks"].append(attack_data)
        
        with open(filename, 'w') as f:
            json.dump(malicious_data, f, indent=2)
        
        print(f"\n📄 All malicious inputs exported to: {filename}")
        return filename


def main():
    """Main CLI interface"""
    
    parser = argparse.ArgumentParser(
        description="Automated Security Testing Tool for Good_Agent.py"
    )
    parser.add_argument("--test-type", default="all", 
                       choices=["all", "single", "batch"],
                       help="Type of test to run")
    parser.add_argument("--attack-type", default=None,
                       help="Specific attack type to test (for single test)")
    parser.add_argument("--attack-types", default="prompt_injection,data_exfiltration,social_engineering",
                       help="Comma-separated attack types (for batch test)")
    parser.add_argument("--batch-size", type=int, default=2,
                       help="Number of attacks per type (for batch test)")
    parser.add_argument("--tenant-id", default="tenantA",
                       help="Target tenant ID")
    parser.add_argument("--clearance", default="INTERNAL",
                       help="Target clearance level")
    parser.add_argument("--role", default="analyst",
                       help="Target user role")
    parser.add_argument("--output-file", default=None,
                       help="Save detailed report to JSON file")
    parser.add_argument("--show-metadata", action="store_true",
                       help="Show detailed metadata for each test")
    parser.add_argument("--export-malicious", action="store_true",
                       help="Export all malicious inputs to JSON file")
    parser.add_argument("--malicious-file", default=None,
                       help="Custom filename for malicious inputs export")
    
    args = parser.parse_args()
    
    # Initialize tester
    tester = SecurityTester()
    
    # Run tests based on type
    if args.test_type == "all":
        results = tester.test_all_attack_types(args.tenant_id, args.clearance, args.role)
    elif args.test_type == "single":
        if not args.attack_type:
            print("❌ Error: --attack-type required for single test")
            sys.exit(1)
        result = tester.test_single_attack(args.attack_type, args.tenant_id, args.clearance, role=args.role)
        results = [result]
    elif args.test_type == "batch":
        attack_types = [t.strip() for t in args.attack_types.split(",")]
        results = tester.test_batch_attacks(attack_types, args.batch_size, args.tenant_id, args.clearance, args.role)
    
    # Show detailed metadata if requested
    if args.show_metadata:
        for result in results:
            tester.print_detailed_metadata(result)
    
    # Generate and print report
    tester.print_report()
    
    # Save detailed report if requested
    if args.output_file:
        report = tester.generate_report()
        with open(args.output_file, 'w') as f:
            json.dump(report, f, indent=2)
        print(f"\n📄 Detailed report saved to: {args.output_file}")
    
    # Export malicious inputs if requested
    if args.export_malicious:
        tester.export_malicious_inputs(args.malicious_file)


if __name__ == "__main__":
    main()
