global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'vecsec-monitor'
    environment: 'sandbox'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "vecsec_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # VecSec Agent metrics
  - job_name: 'vecsec-agent'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9091']
        labels:
          service: 'vecsec-agent'
          component: 'security-detection'
          namespace: 'vecsec'

  # VecSec Testing metrics
  - job_name: 'vecsec-tests'
    static_configs:
      - targets: ['localhost:9092']
        labels:
          service: 'test-framework'
          component: 'security-testing'

# Remote write configuration for long-term storage (optional)
# remote_write:
#   - url: 'https://your-storage-backend/api/v1/write'

